/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** A simple ping function to verify the NAPI setup. */
export declare function ping(name: string): string
export interface JsValidationMarker {
  line: number
  message: string
}
export interface JsValidationResult {
  isValid: boolean
  markers: Array<JsValidationMarker>
}
export interface JsSearchResult {
  idx: number
  score: number
  id?: string
  metadata: any
}
export interface JsKbInfo {
  count: number
  dim: number
  hnswReady: boolean
}
/** Validates a document using the default profile. */
export declare function validateSync(text: string): JsValidationResult
export declare function loadKnowledgeBase(path: string): Promise<number>
export declare function loadKbCache(path: string): Promise<number>
export declare function saveKbCache(path: string): Promise<void>
export declare function buildIndex(): Promise<number>
export declare function search(query: Float32Array, topK: number): Promise<Array<JsSearchResult>>
export declare function kbInfo(): Promise<JsKbInfo>
